### PR TITLE
Update NAMESPACE

### PR DESCRIPTION
**Pull request by dan87134**
is_condition is listed in the documentation as an rlang function but it is not exported from rlang. It is available as rlang:::is_condition though.

### CODE REVIEW

**Comment by lionel-** [comment]
Good catch. The NAMESPACE file is automatically generated. You need to add an `@export` statement above the function and redocument.

**Comment by dan87134** [comment]
Thanks... by "you" do you mean me?... I'm just using the public install from https://www.r-project.org/

**Comment by lionel-** [comment]
Yes if you would like this PR merged. But I can do it that's no worries at all.

**Comment by dan87134** [comment]
Ah, I see what to do now... next time :-)

**Pull request closed without merging**
